### PR TITLE
Add support for the PocketGo2 v2 menu button

### PR DESCRIPTION
**Pull request by nl255**
I tested this on my PG2v2 and it works just fine with both the power button and the menu button able to bring up the menu.

### CODE REVIEW

**Comment by m45t3r** [comment]
@nl255 Huh... I can merge the button changes, but I don't like the solution for `libpng16`. There should probably be a better solution (static compilation?), or at least it should be optional.

**Comment by m45t3r** [comment]
At least, it would be interesting to find `libpng16` from system and make a copy to the OPK, so we make sure that we're using the correct version.

Not the cleanest solution BTW, but it should be better than embedding a copy of `libpng16` to the repository.

**Comment by nl255** [comment]
When I made the pull request it was only for the button support.  The other two commits (libpng and the shell script to work around a gmenu2x bug) were intended just for my repo but it added those commits to the PR automatically.

As for libpng, unfortunately Rogue firmware (and presumably stock firmware) only have libpng14, not libpng16.  In addition, the shell script is necessary since even just using env=FOO=BAR echo "hello world" for the Exec line causes all sorts of problems in gmenu2x (won't create the corresponding file in .gmenu2x/sections/emulators, won't save the rom path, and if you try to edit it even if you don't change anything it will move the icon from emulators to apps).  The only way I could get it to compile with libpng14 was to use the toolchain from 2014 which apparently doesn't support profiling.  Statically linking libpng or even everything might be better (certainly less ugly) but opendingux-gcw0-toolchain.2020-10-01.tar.gz doesn't seem to have static libraries.

**Comment by m45t3r** [comment]
@nl255 I am going to merge the button changes.

As for the `libpng16` issue, I think we can discuss a solution in the Issues or Discord if you want, since I don't like the current solution. I really want to avoid at least committing a binary file in the repository, and I think a better solution should exist.

**Comment by m45t3r** [comment]
> I am going to merge the button changes.

Done with 12b1ec68ac6f43314d727f846ffa0ab835543ce0. Thanks @nl255.

**Comment by nl255** [comment]
Ok, sounds good.  For now at least your PocketSNES.opk: https://github.com/od-contrib/buildroot-rg350-old-kernel build seems to work just fine.

**Pull request closed without merging**
