### PR TITLE
Port apu/soundux from snes9x2005

### PR DESCRIPTION
**Pull request by m45t3r**
This should bring some improvements to sound quality.

https://github.com/libretro/snes9x2005/pull/27
https://github.com/libretro/snes9x2005/pull/28
https://github.com/libretro/snes9x2005/pull/29
https://github.com/libretro/snes9x2005/pull/39

### CODE REVIEW

**Comment by m45t3r** [comment]
Build from commit 11f7802 (not PGO optimized): [PocketSNES.zip](https://github.com/m45t3r/PocketSNES/files/5434039/PocketSNES.zip)

**Comment by DrUm78** [comment]
I merged your code for the FunKey S device on [my fork](https://github.com/DrUm78/PocketSNES/commits/drum78) and it works quite well I must say, so thank you for the huge work! Maybe the sound is a bit more saturated than before but not very sure for now as my device does not have any headphone jack.

That finally fixes that annoying extended note bug from 1.43 with Star wars and Mortal Kombat series among others.
However I did not take https://github.com/m45t3r/PocketSNES/pull/3/commits/60006df3c2758479aa2b9b36b01d30b45a6c9c22 as it really degrades the sound quality (which becomes very saturated and dirty with that commit).

In its current state, it's already quite good (I haven't tested many games so far though), anything to add on your side to merge the PR (except fixing the last commit maybe)?

**Comment by m45t3r** [comment]
> I merged your code for the FunKey S device on [my fork](https://github.com/DrUm78/PocketSNES/commits/drum78) and it works quite well I must say, so thank you for the huge work! Maybe the sound is a bit more saturated than before but not very sure for now as my device does not have any headphone jack.
> 
> That finally fixes that annoying extended note bug from 1.43 with Star wars and Mortal Kombat series among others. However I did not take [60006df](https://github.com/m45t3r/PocketSNES/commit/60006df3c2758479aa2b9b36b01d30b45a6c9c22) as it really degrades the sound quality (which becomes very saturated and dirty with that commit).
> 
> In its current state, it's already quite good (I haven't tested many games so far though), anything to add on your side to merge the PR (except fixing the last commit maybe)?

Interesting. I can't promise anything, but I will try to merge the changes here them and do a new release.

**Comment by m45t3r** [comment]
Well, even reverting the changes in [60006df](https://github.com/m45t3r/PocketSNES/pull/3/commits/60006df3c2758479aa2b9b36b01d30b45a6c9c22) the sounds looks completely wrong in RG350. The only reason I can think is because the FunKey version should be based on a different version than the one of this fork.

**Comment by DrUm78** [comment]
Indeed the codebase is slighthly different but I dunno why have a "clean" sound without that commit and wrong with it. 🤔

**Comment by DrUm78** [comment]
I mean, the FunKey S port has some perks of course but is based on [Nebuleon's 1.43+SDD1](https://github.com/DrUm78/PocketSNES/commit/985969a9f3487ae8e2421b09567fd7e22fb10a5c).

**Comment by m45t3r** [comment]
I think the fact that it is working with the reversal of [60006df](https://github.com/m45t3r/PocketSNES/pull/3/commits/60006df3c2758479aa2b9b36b01d30b45a6c9c22) strange actually, because the only thing it does is removing Stereo from settings because it is now useless (there is no support for mono in the code from `snes9x2005`).

**Comment by DrUm78** [comment]
I know that's not the topic but as you did not enable bug report, here it is:
This commit break compatibility for Jokkyou Parodius on RG350 and FunKey S: 4e4b7eb036eb33e35b6f3e5638e2d9365ed33c39
When launching the ROM, we only hear the Konami sound with a black screen and that's it. Works perfectly without this commit.

**Comment by DrUm78** [comment]
> I think the fact that it is working with the reversal of [60006df](https://github.com/m45t3r/PocketSNES/pull/3/commits/60006df3c2758479aa2b9b36b01d30b45a6c9c22) strange actually, because the only thing it does is removing Stereo from settings because it is now useless (there is no support for mono in the code from `snes9x2005`).

Ok will try again to apply this commit then and will let you know.

**Comment by DrUm78** [comment]
> Build from commit [11f7802](https://github.com/m45t3r/PocketSNES/commit/11f7802b417fc4ffdfea46a353647991f526c12f) (not PGO optimized): [PocketSNES.zip](https://github.com/m45t3r/PocketSNES/files/5434039/PocketSNES.zip)

I tested this build on my RG350P and it's quite good, it's not on your side? It does not have this commit btw https://github.com/m45t3r/PocketSNES/pull/3/commits/60006df3c2758479aa2b9b36b01d30b45a6c9c22.
EDIT: A bit more crackling on RG350 than on FunKey S for some reasons though, not sure why. That's crystal clear on the FunKey S.

**Comment by m45t3r** [comment]
> > Build from commit [11f7802](https://github.com/m45t3r/PocketSNES/commit/11f7802b417fc4ffdfea46a353647991f526c12f) (not PGO optimized): [PocketSNES.zip](https://github.com/m45t3r/PocketSNES/files/5434039/PocketSNES.zip)
> 
> I tested this build on my RG350P and it's quite good, it's not on your side? It does not have this commit btw [60006df](https://github.com/m45t3r/PocketSNES/commit/60006df3c2758479aa2b9b36b01d30b45a6c9c22). EDIT: A bit more crackling on RG350 than on FunKey S for some reasons though, not sure why. That's crystal clear on the FunKey S.

Curious how you got [11f7802](https://github.com/m45t3r/PocketSNES/commit/11f7802b417fc4ffdfea46a353647991f526c12f) to build. You did a modification right? Because [11f7802](https://github.com/m45t3r/PocketSNES/commit/11f7802b417fc4ffdfea46a353647991f526c12f) doesn't build for me with the following error:

```
menu/main.cpp:569:18: error: ‘struct SSettings’ has no member named ‘Stereo’
  569 |         Settings.Stereo = TRUE;
      |                  ^~~~~~
```

Commenting this line makes it work again.

Anyway, I tried to build it again and no dice, the sound is horrible on my RG350P with the https://github.com/eduardofilo/RG350_adam_image/ firmware. So maybe it is something from either the new kernel or the new toolchain? I am using this one: http://od.abstraction.se/opendingux/toolchain/opendingux-gcw0-toolchain.2021-10-22.tar.xz

**Comment by DrUm78** [comment]
Oh yeah I had to comment the stereo one and [this line](https://github.com/DrUm78/PocketSNES/blob/e06280af382bd1ec870734aa33d72a0d77825aa7/pocketsnes/snes9x/soundux.cpp#L777).

**Comment by DrUm78** [comment]
For the RG350 build, I just used the one you posted above as I can't compile for MIPS right now, and I have Rogue FW (so not Beta).

**Comment by m45t3r** [comment]
> This commit break compatibility for Jokkyou Parodius on RG350 and FunKey S

To be clear, the idea here is to improve sound in general. Those forks of snes9x are always going to be a trade-off between performance/audio quality/compatibility. There is no way to have it all, since all changes can break a random game somewhere.

**Comment by DrUm78** [comment]
Yeah I know but what is interesting here is that it's caused by the SA-1 fixes and that the bug does not occur with the Libretro 2005 core.

**Comment by m45t3r** [comment]
Seems to be working now.

**Comment by DrUm78** [comment]
Yeah that's still working for me with the last cleanup. 👍
BTW, your OPK seems to work fine on my RG350 with RogueCFW. I will publish the update on the FunKey S too.

Thanks again for all your work. ;)

**Pull request merged**
